# Generated by Django 5.2.17 on 2026-08-16 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication_recruiter_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Resume', max_length=255)),
                ('file', models.FileField(upload_to='resumes/')),
                ('is_primary', models.BooleanField(default=False)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('skills', models.TextField(blank=True, default='')),
                ('education', models.TextField(blank=True, default='')),
                ('experience', models.TextField(blank=True, default='')),
                ('projects', models.TextField(blank=True, default='')),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
